- src/components/SwatchPaletteWidget/SwatchPaletteWidget.js
- src/components/SwatchPaletteWidget/_swatch-palette-widget.scss
- src/pages/elements/color.mdx
Closes #101
This PR contains some style fixes for the color switcher component. One thing to note though is that the space between the copy and the color switcher is slightly larger than 16px due to the margin applied to every text paragraph
**Changed**
- top padding of sticky color switcher for mobile breakpoints
**Removed**
- content switcher button borders
- color switcher sticky container top padding
> fix: color switcher style bugs

- src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
Closes #92 
Adds a link to Design Kit to the bottom of the left-hand nav by shadowing ResourceLinks file
**New**
- nav link
> feat: add link to bottom of left hand nav

- src/components/TypeFaceSubFamilies/_typeface-sub-families.scss
- src/components/TypeTester/TypeTester.js
- src/components/TypeTester/_type-tester.scss
- src/pages/elements/typeface.mdx
Closes #84
Closes #130 
Closes #131 
This PR addresses several style issues on the Typeface page
**New**
- responsive font size (values lifted from current IDL site)
**Changed**
- Replace `<InputRange>` with Carbon `<Slider>`
- typeface page lead video ID
> fix: typeface page styles and include Carbon Slider

- src/pages/index.mdx
This updates the Design Kit card url on the homepage. Information for the Digital Design Kit has been moved to [Getting Started: Designers](https://www.ibm.com/standards/web/getting-started/designers.html#get-the-kit) and the original page has been removed from the site.
**Changed**
- Design Kit card url [kennylam@dd2ef1ba9d17cbea9293134f8f6749c564ebc901]
> chore(url): update Digital Design Kit url

- src/styles/_philosophy.scss
Closes #136
This PR enables the `fluid` option for the type mixin for body copy on the Philosophy page
> fix(philosophy): enable fluid type mixin

- src/pages/elements/logos/rebus.mdx
**Removed**
- the unnecessary  'the' in this sentence "Today we still **the** use the Rebus which has since been adjusted to meet the requirements of different mediums..."
> chore: remove unnecessary the in rebus.mdx

- src/components/HomepageVideo/_homepage-video.scss
Closes #149
This PR fixes the mobile margins for the homepage video CTA
> fix(homepage-video): reset mobile margin

- src/components/NonLatinScripts/_non-latin-script.scss
- src/components/TypeFaceSubFamilies/TypefaceSubFamilies.js
- src/components/TypeTester/TypeTester.js
Closes #138
This PR modifies the non-Latin script stylesheet to avoid cutoff issues on multiple browsers
**New**
- set custom height rules and line height rules for Devanagari, Arabic, Thai
**Changed**
- replace script specific style overrides and set consistent spacing rules
- remove console errors
**Removed**
- conflicting `!important` overrides
> fix(non-latin-script): avoid script cutoff

- src/data/nav-items.yaml
- src/pages/elements/pictograms/contribute.mdx
- src/pages/elements/pictograms/design.mdx
- src/pages/elements/pictograms/usage.mdx
Closes #164
This PR renames the "overview" tab for the pictograms page to "design"
> fix(pictograms): rename page

- src/components/HomepageVideo/_homepage-video.scss
Closes #161 
This PR fixes the landing page styles so that the links overlaid on the video appear correct on iOS devices
**Changed**
- default `flex-basis` rule
> fix(homepage-video): change default flex-basis

- src/components/NonLatinScripts/_non-latin-script.scss
Closes #138
This PR increases the line height for all non-Latin type examples
> fix(non-latin-script): increase line height for non latin type examples

- src/pages/elements/pictograms/contribute.mdx
Closes #182
This PR adds missing links for the Design and production guidelines section on the pictograms page
> fix(pictograms): add links for design and production guidelines

- src/components/TypeFaceSubFamilies/_typeface-sub-families.scss
Closes #166
This PR changes the typeface sub families styles to apply column width only on larger screen sizes
> fix(typeface-sub-families): avoid line breaks on mobile

- src/components/TypeTester/TypeTester.js
Closes #84
This PR adds a check for the current window size in the initial type tester component state to set the correct type size multiplier
> fix(TypeTester): reduce default slider value for smaller screens

- src/components/Carousel/_carousel.scss
- src/components/HomepageTile/HomepageTile.js
- src/pages/index.mdx
Closes #108
This PR addresses several homepage layout issues related to card ratios at different screen sizes, image ordering, and spacing
**New**
- `<HomepageTile>` supports an object of ratios for the `ratio` prop (`ratio={{ default: '1:1', sm: '2:1', md: '3:2' }}`), linked to Carbon breakpoints
**Changed**
- avoid column gutter at small screen sizes
- copy fixes
> fix(index): resolve homepage layout bugs

- src/components/Carousel/Carousel.js
- src/pages/elements/color.mdx
- src/pages/index.mdx
Closes #246
This PR changes the Carousel component initial `autoplay` state to read from `props.autoPlay` instead of `props.autoplay`. The homepage and color page carousels should now autoplay properly
> fix(Carousel): use camelcased autoplay attribute

- src/styles/_ibm-cookies.scss
- src/styles/index.scss
Closes #240 
There isn't really an easy way to test this without inserting dummy HTML. I copied what IBM Brand Center did, so pretty sure this will work.
> chore: add styles for ibm inserted cookie prefs button

- src/pages/elements/type-basics.mdx
Closes #261
This PR fixes a typo in the type basics page alignment section copy
> fix(type-basics): alignment copy edit

- src/components/Carousel/_carousel.scss
- src/styles/_homepage.scss
Closes #263
This PR adjusts carousel styles so that absolute positioned `img` children in the carousel will not collapse due to its parent being relative positioned and having percentage based height. We set padding instead of height to maintain the parent container's dimensions when the `img` children are absolutely positioned
> fix(color-page): prevent carousel from collapsing on mobile

- src/components/SwatchPaletteWidget/SwatchPaletteWidget.js
Closes #273
Related https://github.com/carbon-design-system/carbon-website/pull/124/
This PR modifies the content switcher in `<SwatchPaletteWidget>` to account for upstream breaking changes (ref https://github.com/carbon-design-system/carbon/pull/3302/). Since we no longer receive the deprecated `name` prop and only receive selected index on change, we use the existing hard coded `colorFormats` array to show the correct color info
**Changed**
- color format switcher logic (now relying on returned index instead of switch name due to #3302)
> fix(SwatchPaletteWidget): restore format switching functionality

- src/pages/elements/icons/usage.mdx
👋 I fixed a typo on the icon usage page. I assume `0px` was supposed to be `20px` 😅
> docs: fix icon size typo

- .circleci/config.yml
- package.json
An update dependancy has a minimum node version of `8.12` but because we're tied to `8.11` it fails circle-ci.
This also adds the "engine" key to our package.json to ensure the cloud foundry builder uses the same version as circle-CI
> chore: specify node version and update ci version

- gatsby-node.js
Gatsby generates source-maps even production. This is an issue with our dynamic icon strategy which generates hundreds of javascript files.
This removes source-maps in when in production.
also [disabled for Carbon](https://github.com/carbon-design-system/carbon-website/pull/1144)
> chore: disable source-maps in production

- src/components/OverviewCard/OverviewCard.js
- src/components/OverviewCard/overview-card.scss
Closes #518 
Makes chart overview cards have a link out button with tooltip like the icon overview cards.
**Changed**
- if link is external, overview card now has a small link at the bottom right corner w/ a launch icon + tooltip on hover (internal links will remain as is)
- made tooltip align at the end bc otherwise it cuts off after a certain breakpoint (`xl`/`1312px`) bc there's not enough margin on the side. This can be seen in the icon overview cards. Not sure if this is the solution we want.  ⬅️ _Any feedback?_
> feat: update chart overview cards

- src/pages/illustration/isometric-style/design.mdx
Closes #539 
**Changed**
- Uses correct `DoDont` component for spacing
> fix: illustration isometric page dodont

- src/pages/illustration/overview.mdx
Forgot to remove this card along with the other cards on the Usage tabs.
> Remove Resource card from Illustration: Overview

- src/components/SwatchPaletteWidget/_swatch-palette-widget.scss
- src/pages/help/faq.mdx
@sadekbazaraa @mjabbink one thing to note is that the `1px` space blends in since it invariably comes after the lightest color in the pallete. Not that we'd want to do anything different, it's just difficult to see.
> fix: tweak pallete space closes #608

- src/pages/color.mdx
In “Combinations to avoid” section  — replaced the single straight quote marks with apostrophes in “Do Not” captions
Closes #
**New**
**Changed**
**Removed**
> Replace straight quotes with proper apostrophes

- src/components/SVGLibraries/PictogramLibrary/PictogramLibrary.js
We got a null alias from one of the carbon pictograms
> fix: pictogram filtering is broken

- src/pages/illustration/overview.mdx
Removed "Resources" anchor link since there is no resources section anymore.
> IDL - Illo Overview - remove anchor

- src/pages/iconography/ui-icons/contribute.mdx
Updating UI icon production and contribution guidance to better reflect our production practices. Will make the same changes to Carbon site UI icon guidance: https://github.com/carbon-design-system/carbon-website/pull/1600
**Changed**
- updated Contribution section to match updates made to Carbon site
**Removed**
- removed mention of creating 16px icons and exporting from Sketch section
> [IDL] UI icon production guidance update

- src/pages/2x-grid.mdx
The resource card "2x grid in UI: basics" was broken, the carbon page is now called overview instead of basics.
> Fix broken link

- src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
Update the resource link in the left nav for "Carbon libraries" from the current "https://www.carbondesignsystem.com/resources/#theme-libraries"  to the correct: :"https://www.carbondesignsystem.com/designing/kits/sketch"
> [IDL] Update left nav link to carbon libraries

- src/components/TypeTester/_type-tester.scss
- src/components/TypesetStyle/_typeset-style.scss
Closes #755 
Compare to current positioning: 
1. `/typography/typeface`
2. `/typography/type-specs-ui`
> fix: typetester and typeset style vertical alignment

- src/components/Carousel/_carousel.scss
- src/components/ColorBlock/color-block.scss
- src/components/HomepageVideo/_homepage-video.scss
- src/components/NonLatinScripts/_non-latin-script.scss
- src/components/TypeFaceSubFamilies/_typeface-sub-families.scss
- src/components/TypeTester/_type-tester.scss
- src/components/TypesetExample/_typeset-example.scss
- src/components/TypesetStyle/_typeset-style.scss
- src/styles/_homepage.scss
- src/styles/_images.scss
- src/styles/_typography.scss
Closes #795
In some `.scss` files, a `rem(<pixel value>)` has been used to calculate values in rem units. However, there is no internal Sass mixin called `rem()`, nor is there an external library as a dependency that uses this notation. Therefore all of the values expressed with `rem()` are causing an error in the browser.
**Changed**
- all `rem()` notations to actual rem values
Some before and after screenshots:
> Fix/sass mixin bug by replacing with rem values, closes #795

- src/pages/color.mdx
**Changed**
- The `IBM color palette` resource card link was broken. I updated it so it will download and open the correct ZIP with the v02.1 color files.
-----
**Testing**
- Make sure you can download and open the zip file from the `IBM color palette` resource card.
- `Color page` -> `Resources section` -> `IBM color palette` resource card
> (fix) broken link for color files

- src/components/SwatchPaletteWidget/_swatch-palette-widget.scss
- src/styles/Grid.module.scss
This PR fixes black outline from the swatch palette widget #920 and issue with images not being rendered properly on the What's new page #935 .
Closes #935,  closes #920
> fix: black outline from the swatch palette + fix missing images

- src/pages/iconography/pictograms/design.mdx
Current link doesn't work, most likely because Sketch phased out short links some time ago. Updated it to point to IBM Design Language V2 library.
> Update link for Sketch library on Pictograms page

- src/pages/typography/typeface.mdx
Removed hyphen in open-source. We don’t use the hyphen anywhere when we mention open source. Even on this page in header underneath or on the About Carbon pages.
Closes #
**New**
**Changed**
**Removed**
> Changed versus to vs.

- src/pages/typography/typeface.mdx
Removed resource card for Noto Japanese here: https://www.ibm.com/design/language/typography/typeface#asian-scripts
Closes #
**New**
**Changed**
**Removed**
> Removed resource card for Noto Japanese

- src/pages/typography/typeface.mdx
Second column https://www.ibm.com/design/language/typography/typeface#language-support
Closes #
**New**
**Changed**
**Removed**
> Added “Japanese” to the Language support list

- src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
- src/pages/iconography/pictograms/contribute.mdx
- src/pages/typography/type-specs-ui.mdx
Closes [Brand Issue #5](https://github.com/ibm-brand/design-language/issues/5)
Broken links fix for IDL Library sketch workspace.
**Changed**
- Correct IDL Library links on:
- left nav-bar link
- typography/type-specs-ui#resources
- color#resources
**Removed**
- Broken links
> fix: changed broken sketch links for idl library

- src/components/SVGLibraries/AppIconLibrary/AppIconLibrary.module.scss
Closes #1009
Updates app icon filter row positioning
**Changed**
- changing position `top: 7rem` to `top: 6.95rem` to acconut for the pixel difference.
Make sure the tabs look good
> fix: update top positioning for filter in app icons tab

- package.json
- yarn.lock
- switcher link updates
closes #1047
> chore: bump theme to 2.1.6

- gatsby-node.js
- yarn.lock
Verify that `ibm--z` and `ibm--z--partition` do not show up in the pictogram index. 
Relevant slack convo: 
https://ibm-studios.slack.com/archives/GCQ5R263T/p1646931614070099
> fix(design): remove ibm--z and ibm--z--partition from website index

- src/pages/infographics/infograms/index.mdx
Closes [Brand Center #10](https://github.com/ibm-brand/design-language/issues/10)
Just a little typo correction on the Infograms page
**Changed**
- "maginal" to "marginal" in the Infograms page description
> fix: typo on infogram page description

- src/pages/ibm-logos/8-bar.mdx
Closes #1145 (Brand [#11](https://github.com/ibm-brand/design-language/issues/11)
Change to solve 404 error opening the [Third party logo usage](https://www.ibm.com/design/language/ibm-logos/8-bar/#third-party-logo-usage) resource card file on the same tab.
**Changed**
- [Third party logo usage](https://www.ibm.com/design/language/ibm-logos/8-bar/#third-party-logo-usage) resource card link chaged (from relative path to absolute path).
> fix: changed file path from relative to absolute due to 404

- .github/workflows/deploy.yml
Closes #
https://github.com/carbon-design-system/carbon/issues/12186
This PR introduces an action to publish the website to the `gh-pages` branch. The IBM Cloud publishing has been kept intact for now until the route has been updated to be handled by the corporate webmaster team.
**Changed**
- Updated `deploy.yml` to publish to `gh-pages` branch
- Added concurrency rule to deployments
- Added repo check for IBM cloud publishing
> chore(github-pages): add workflow for publishing to gh-pages

- .github/workflows/deploy.yml
This addresses https://github.com/carbon-design-system/carbon/issues/12186.
This PR adjusts the deploy script to build to a US geo object storage instead of Cloud Foundry. 
COS environment variables have already been added to this repository.
> chore(github-pages): update to upload to s3

- src/pages/data-visualization/charts.mdx
Closes #1167
**Removed**
- Removed "Design only" tag from Heatmap thumbnail under Correlations section
> fix: removes "Design only" tag from Heatmap

- src/data/app-icons.yaml
The icon for File Storage for VPC is incorrectly labelled currently as "Block" Storage for VPC, this PR will fix the name.
(Icon on the right is the file storage icon)
**New**
- N/A
**Changed**
- Yaml for name of icon
**Removed**
- N/A
> Update incorrect name for File Storage for VPC

- src/pages/ibm-logos/rebus.mdx
Closes [358](https://github.com/ibm-brand/center/issues/358) (Brand Center Issue)
Update Box link at patterns section under IBM logos, Rebus page
**Changed**
- Update Box link on Eye-Bee-M patterns card at patterns section.
> feat: update Box link at patterns section

- src/components/SwatchPaletteWidget/_swatch-palette-widget.scss
Closes #1200 
Fixes the problem with cutting and pasting hex codes
- Added `user-select: all` on the element containing hex value in the `SwatchPaletteWidget`.
> fix: fixed the problem with cutting and pasting hex codes

- src/pages/gallery/index.mdx
…, since relative links resolved wrongly
Closes Brand [issue 359](https://github.com/ibm-brand/center/issues/359) 
New gallery assets got their `src` URLs badly resolved when used relative paths on code.
**New**
- N/A
**Changed**
- Fixed `src` URLs for gallery videos using their absolute path.
> fix(gallery): edited video src to absolute links

- gatsby-node.js
[Internal issue here](https://github.ibm.com/brand/Pictograms/issues/192)
> These three may or may not be replaced by new artwork, which is why we don't want to fully deprecate them just yet.
https://ibm-studios.slack.com/archives/C06110G3J9E/p1696868173709569
- Verify `watsonx--ai.svg`, `watsonx--data.svg`, and `watsonx--governance.svg` do not show on the pictogram index/library
> fix(pictograms): hide watsonx pictograms from IDL website

- src/pages/data-visualization/design/basics.mdx
- Fixed a link error to the IBM color palette file on the Data visualization > Design page
> fix: bug fix for link in resource card on Data viz page

- src/pages/resources.mdx
- Fixed a link error to the IBM color palette file on the Resources page > Color section
> fix: bug fix for link in resource card on Resources page

- src/pages/2x-grid.mdx
- src/pages/resources.mdx
Closes: N/A (Issue pointed out on internal Slack channel)
Removed a resource card for Thinking with type on the 2x grid page.
Page seems to be down for good and no substitute was pointed.
**New**
- N/A
**Changed**
- N/A
**Removed**
- "Thinking with type: baseline grid" resource card removed due to broken link.
> fix(2xgrid): removed card where page linked is down

- src/pages/2x-grid.mdx
- src/pages/animation/overview.mdx
- src/pages/color.mdx
- src/pages/data-visualization/design/basics.mdx
- src/pages/iconography/app-icons/design.mdx
- src/pages/iconography/ui-icons/contribute.mdx
- src/pages/layout/tips-and-techniques.mdx
- src/pages/resources.mdx
Closes N/A
Found wrong links pointing to old paths like `type-specs-ui` and `/elements` and broken links on multiple pages.
**New**
- N/A
**Changed**
- Links on both 2x Grid and Layout/Tips and Techniques pages
- Links on multiple pages pointing to carbondesignsystem.com
**Removed**
- N/A
> fix(multple): edited broken and incorrect links

- src/pages/typography/typeface.mdx
Closes Urgent issue for Brand 
Fix link on resource card for Plex Math on the typeface page
**New**
- N/A
**Changed**
- fixed link for Plex Math section in a resource card
**Removed**
- N/A
> Fix(typeface): changed the link for plex math resource card

- src/gatsby-theme-carbon/components/Footer/index.js
- src/pages/color.mdx
- src/pages/iconography/pictograms/contribute.mdx
- src/pages/iconography/pictograms/design.mdx
- src/pages/iconography/ui-icons/design.mdx
- src/pages/resources.mdx
Closes [Brand issue #620](https://github.com/ibm-brand/center/issues/620)
Link fixes on footer and on Resources page + subsection removal
**New**
- N/A
**Changed**
- Changed title from Eye-Bee-M to Rebus in a card on the IBM Logos section from Resources page as well as it's box link
- Fixed the ibm-brand channel link in the IDL footer
- Plenty of links on resources cards pointing to Sketch materials were updated to Figma links
- Other broken links were fixed
**Removed**
- Type alternatives subsection on the Typography section from the Resources page, since IBM Plex Traditional Chinese is already available
> Broken links + Rebus card and Slack link updates

- gatsby-node.js
- src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js
Closes [issue 1402](https://github.com/carbon-design-system/design-language-website/issues/1402)
Reinstate the `ibm--z` pictogram in `design-language-website`
**New**
- N/A
**Changed**
- Update areas that were hiding the `ibm--z` pictogram
**Removed**
- N/A
> chore: reinstate IBM Z pictogram

- .github/workflows/deploy.yml
Closes #1417 
Bumped old max size on Node options for S3 deployment
**Changed**
- Changed `--max_old_space_size` from 4GB to 7GB on `deploy.yml`
> ci(deploy.yml): bumped max old space size to close to 7GB limit

- src/gatsby-theme-carbon/components/Switcher/Switcher.js
- src/gatsby-theme-carbon/components/Switcher/Switcher.module.scss
- src/gatsby-theme-carbon/components/Switcher/index.js
Closes [Brand issue #775](https://github.com/ibm-brand/center/issues/755)
Remove broken link button from waffle menu
**New**
- N/A
**Changed**
- N/A
**Removed**
- Broken link button from waffle menu
> chore(switcher-shadowed): add shadowed switcher to remove equality link
