- .github/CONTRIBUTING.md
- src/gatsby-theme-carbon/components/Footer.js
Closes #
**New**
**Changed**
**Removed**
> chore: update docs

- src/pages/elements/2x-grid-ui.mdx
- src/pages/elements/2x-grid.mdx
- src/pages/elements/color-ui.mdx
- src/pages/elements/color.mdx
Added .mdx, no images or components yet.
> docs: adding IDL markdown

- package.json
- yarn.lock
Closes #
**New**
**Changed**
**Removed**
> chore: bump theme version

- src/pages/elements/2x-grid-ui.mdx
- src/pages/elements/icons/contribute.mdx
- src/pages/elements/icons/overview.mdx
- src/pages/elements/logos/8-bar.mdx
- src/pages/elements/logos/rebus.mdx
> Docs  adding more pages

- src/pages/philosophy/pov.mdx
- src/pages/philosophy/principles.mdx
- src/styles/_philosophy.scss
- src/styles/global.scss
> feat: Philosophy page

- src/components/HomepageTile/_homepage-tile.scss
- src/components/HomepageVideo/_homepage-video.scss
- src/pages/index.mdx
Closes #80 
Closes #81
**Changed**
- Updated background color for homepage card
- Fixed sizing issues with icons on homepage
> fix: homepage style bugs

- src/pages/elements/logos/rebus.mdx
Closes #154 
**Changed**
`differerent mediums`
> fix(elements): Typo in rebus content, resolves #154

- .circleci/config.yml
- .circleci/manifest.production.yml
- .circleci/manifest.staging.yml
- package.json
Updates config so site should deploy to staging when merged 🙏 
Updated build:prefix command to move files into correct folders.
> chore: update build command update circle ci config

- .circleci/manifest.production.yml
- .circleci/manifest.staging.yml
Closes #
**New**
**Changed**
**Removed**
> Update circle ci

- Staticfile
Closes #
**New**
**Changed**
**Removed**
> chore: add staticfile

- .circleci/config.yml
THIS WILL DEPLOY THE NEW SITE LIVE
> feat: update deployment config to deploy live

- src/pages/philosophy/principles.mdx
Closes #243
Markdown fix to make the entire word and sentence bold
> fix(principles): bold entire sentence

- src/pages/elements/typeface.mdx
Refs #236
This PR updates a hyperlink (only one of the problems found in #236)
> fix(typeface): use correct hyperlink

- README.md
- gatsby-browser.js
- package.json
- src/components/NonLatinScripts/_non-latin-script.scss
- src/components/TypeTester/_type-tester.scss
- src/gatsby-theme-carbon/templates/Homepage.js
- src/pages/index.mdx
- src/styles/plex-variants-production.scss
- src/styles/plex-variants.scss
- yarn.lock
closes #245, closes #238, closes #251
> Resource 404 fixes

- src/pages/elements/type-basics.mdx
Closes #262 
This PR fixes the poster for the video on the type basics page
> fix(type-basics): fix video poster

- src/pages/elements/typeface.mdx
Closes #265
This PR updates the link from https://github.com/carbon-design-system/design-language-website/pull/242
> fix(typeface): use more specific hyperlink

- .circleci/config.yml
- .nvmrc
- package.json
> fix: docker image

- src/pages/elements/color.mdx
- src/pages/elements/icons/design.mdx
- src/pages/elements/pictograms/contribute.mdx
- src/pages/elements/pictograms/design.mdx
- src/pages/elements/type-specs-ui.mdx
> fix: update design kit links

- .circleci/config.yml
- yarn.lock
Fixes CI with upstream gatsby fix
> chore: update deps

- .github/workflows/process-images.yml
Closes #
**New**
**Changed**
**Removed**
> chore: add image processing

- .github/workflows/deploy.yml
Closes #
**New**
**Changed**
**Removed**
> fix: install plugins per region

- netlify.toml
> chore: fix redirect syntax

- src/pages/index.mdx
Closes #325
**Changed**
- icon tile title and subtitle
- icon tile icon
> fix(homepage): update icon tile

- src/styles/index.scss
> fix: remove temporary large list band-aid

- package.json
- yarn.lock
> chore: update theme to spacing release

- yarn.lock
Closes #
**New**
**Changed**
**Removed**
> fix: update theme

- src/pages/updates/whats-new.mdx
Closes #
**New**
**Changed**
**Removed**
> fix: whats new content closes #396

- src/pages/ibm-logos/8-bar.mdx
story: https://github.ibm.com/brand/center/issues/682#issuecomment-16985956
updated the RC URLs
> updated 8-bar page RC urls

- src/pages/ibm-logos/8-bar.mdx
story: https://github.ibm.com/brand/Development/issues/9#issuecomment-16988072
> removing get in touch section

- src/pages/iconography/ui-icons/usage.mdx
Close https://github.com/carbon-design-system/gatsby-theme-carbon/issues/701
**New**
**Changed**
**Removed**
> move paragraph of alignment section

- src/pages/iconography/pictograms/library.js
- src/pages/iconography/ui-icons/library.js
> fix: add design tab to frontmatter

- plugins/gatsby-theme-carbon-svgs/components/shared/ActionBar.js
Closes #
**New**
**Changed**
**Removed**
> chore: add type

- src/pages/iconography/ui-icons/design.mdx
corrected 2 typos in ui icons / design resource cards and added alt text for the icons
> update ui icons / design

- plugins/gatsby-theme-carbon-svgs/components/IconLibrary/IconLibrary.js
- plugins/gatsby-theme-carbon-svgs/components/shared/ActionBar.js
- plugins/gatsby-theme-carbon-svgs/components/shared/SvgCard.js
> fix: user ref for icon download

- src/pages/illustration/isometric-style/design.mdx
Closes #
**New**
**Changed**
**Removed**
> Fixed duplicate images

- src/components/NonLatinScripts/NonLatinScripts.js
- src/components/NonLatinScripts/_non-latin-script.scss
- src/components/TypeTester/_type-tester.scss
> fix: use sans in language names

- src/pages/philosophy/principles.mdx
Correcting broken sentence. Aligning the copy with this issue: https://github.com/carbon-design-system/design-language-website/issues/219
Closes https://github.com/carbon-design-system/design-language-website/issues/477
Related to #502
> docs: Fix broken sentence on Philosophy>Principles page

- src/styles/_philosophy.scss
> fix: add pmore space to principles block

- package.json
- plugins/gatsby-theme-carbon-svgs/components/shared/SvgLibrary.module.scss
- src/pages/index.mdx
- yarn.lock
> chore: update theme

- src/pages/iconography/pictograms/contribute.mdx
> update: 528-update-carbon-pictograms-copy

- src/pages/illustration/overview.mdx
> Update hero animated GIF to Vimeo video

- package.json
- yarn.lock
> chore: update carbon

- yarn.lock
Closes #
**New**
**Changed**
**Removed**
> chore: up theme

- src/pages/typography/typeface.mdx
- src/styles/_typography.scss
> fix: 541-language-support-language-list

- src/pages/2x-grid.mdx
> fix: 575-wrong-link-AI-file

- package.json
- yarn.lock
> chore: update dependancies

- src/pages/illustration/flat-style/design.mdx
- src/pages/illustration/line-style/design.mdx
- src/pages/illustration/line-style/usage.mdx
quick fix of some typos
closes #601
> Fix typography: change primes to apostrophes

- src/pages/animation/overview.mdx
Should go to: https://www.carbondesignsystem.com/guidelines/motion/overview
> Fix broken link on "Motion in UI" resource card

- src/pages/illustration/flat-style/design.mdx
Two circles and one square to make a heart.
> Caption update

- .gitignore
- gatsby-node.js
- src/components/SVGLibraries/IconLibrary/IconLibrary.js
- src/components/SVGLibraries/PictogramLibrary/PictogramLibrary.js
> chore: remove unnecessary data from icon metadata

- src/components/OverviewCard/overview-card.scss
**Changed**
- fixed the alignment of the tag in OverviewCard component:
Before fix:
After fix:
> fix: tag alignment in OverviewCard

- src/components/OverviewCard/overview-card-group.scss
Also fixes overview card spacing
> fix: closes #596

- src/pages/iconography/app-icons/production.mdx
- src/pages/iconography/pictograms/contribute.mdx
- src/pages/iconography/ui-icons/contribute.mdx
Updates to code snippets on Contribute tabs for UI Icons and Pictograms pages, as well as Production tab on App Icons page.
> Updating inline code snippets on Iconography pages

- src/pages/color.mdx
- src/pages/help/support.mdx
- src/pages/ibm-logos/8-bar.mdx
- src/pages/ibm-logos/rebus.mdx
- src/pages/iconography/app-icons/design.mdx
- src/pages/iconography/pictograms/design.mdx
- src/pages/iconography/pictograms/usage.mdx
- src/pages/iconography/ui-icons/design.mdx
- src/pages/iconography/ui-icons/usage.mdx
- src/pages/illustration/isometric-style/design.mdx
- src/pages/illustration/isometric-style/production.mdx
- src/pages/illustration/tips-and-techniques.mdx
- src/pages/typography/type-basics.mdx
- Changes all do/dont to use `Don’t` instead of `Do not`
- Also updates a few places where we were using straight quotes for `Don't`
> fix: do dont

- src/components/TypeScaleTable/TypeScaleTable.js
- src/pages/iconography/pictograms/usage.mdx
- src/pages/typography/type-specs-ui.mdx
- src/pages/typography/typeface.mdx
- src/styles/_typography.scss
- yarn.lock
> fix: language support list

- src/pages/illustration/isometric-style/production.mdx
Changing "The reason is because..." to "The reason is that...". First one seems redundant
> [isometric illustration/production] copy change

- src/pages/data-visualization/charts.mdx
- src/pages/data-visualization/images/charts/meter.svg
- add Meter chart to Parts to Whole section, to match Carbon site
- fix link for Stacked chart
- add "Design only" tag to Tree map chart, to match the Carbon site
> [IDL] Data vis: Add new chart to Charts page

- src/pages/iconography/ui-icons/design.mdx
**Changed**
- Updated links for Sketch libraries with their new format (old, short links are going to be depreciated)
> Update links for icons libraries (short links will become invalid soon)

- src/pages/resources.mdx
**Changed**
- Fix broken links
- Update Sketch links to the new format
> Fix broken links and update Sketch links to new format

- src/pages/resources.mdx
Closes #689 
- updates a11y resources link
> fix: a11y resources link

- src/pages/whats-new/index.mdx
> fix(What's New): Removed the gridImages classname from the video

- src/pages/animation/overview.mdx
I think this will fix it, but let's double check
> fix spacing between illustration header and image

- src/components/SwatchPaletteWidget/SwatchPalette.js
- src/components/SwatchPaletteWidget/_swatch-palette-widget.scss
- yarn.lock
closes #776 
closes #756 
closes #731
> chore: upgrade deps

- src/styles/_philosophy.scss
> fix: philosophy video spacing closes #790

- src/pages/iconography/app-icons/production.mdx
> [app icons/production] fix typo

- src/components/SwatchPaletteWidget/_swatch-palette-widget.scss
Closes [#1072](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1072)
There are some custom components on IDL and Brand that need to be updated since the theming PR was merged.
> style: updated colors to sticky-container

- src/components/TypeTester/TypeTester.js
- src/components/TypeTester/_type-tester.scss
- src/components/TypesetStyle/_typeset-style.scss
- src/styles/_typography.scss
Closes #839 
Closes #849
**Changed**
- color tokens
> fix(type): various type demos bg colors

- package.json
- yarn.lock
Closes [#1073](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1073)
You can do this now in mobile!
> chore: update the theme

- src/components/SwatchPaletteWidget/SwatchPaletteWidget.js
Closes [#1078](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1078)
Commentary from previous PR.
> style: added padding to the row

- src/pages/color.mdx
Changed:
- Fixed the IDL sketch library link to the updated url
> fix: IDL sketch library link update

- src/pages/iconography/ui-icons/design.mdx
> fixing 404 link on ui icons page

- gatsby-ssr.js
Closes #
**New**
**Changed**
**Removed**
> chore: defer core metrics script

- src/components/SVGLibraries/PictogramLibrary/PictogramLibrary.js
- src/pages/iconography/pictograms/design.mdx
- src/pages/whats-new/index.mdx
Reverts carbon-design-system/design-language-website#907
> Revert "fix: broken pictogram links"

- gatsby-config.js
- package.json
- src/components/SVGLibraries/IconLibrary/IconCategory.js
- src/components/SVGLibraries/IconLibrary/IconLibrary.js
- src/components/SVGLibraries/PictogramLibrary/PictogramCategory.js
- src/components/SVGLibraries/PictogramLibrary/PictogramLibrary.js
- src/components/SVGLibraries/shared/ActionBar.js
- src/components/SVGLibraries/shared/SvgCard.js
- src/components/SVGLibraries/shared/useColumnCount.js
- yarn.lock
Closes #905
Leverages use-media to detect screen width/column count, modifies tooltip alignment based on that count and a card's index.
> fix: adjust tooltip alignment on last SVG card

- .github/workflows/svgo.yml
- .svgo.yml
- package.json
- src/components/ColorGrid/ColorGrid.js
- svgo.config.js
- yarn.lock
Closes #
**New**
**Changed**
**Removed**
> chore: add svgo action

- package.json
- yarn.lock
This includes upstream changes to the switcher tooltip
> upgrade theme

- gatsby-config.js
- package.json
- src/gatsby-theme-carbon/templates/Homepage.js
- yarn.lock
> chore: update theme, use g100 for callout

- src/pages/iconography/pictograms/usage.mdx
I changed versus to vs.
Closes #
**New**
**Changed**
**Removed**
> Updated versus to vs. in header and anchor link

- src/pages/color.mdx
The image in the color contrast section is broken. I think this may fix it?
> [bug] broken image

- src/pages/iconography/ui-icons/contribute.mdx
Updated URL to the Icons Library
**Changed**
- The URL https://www.carbondesignsystem.com/guidelines/iconography/library to the newer https://www.carbondesignsystem.com/guidelines/icons/library
> Updated URL to the Icons Library

- src/pages/typography/typeface.mdx
Replaced with new text in Asian scripts section since Plex Japanese is near release.
Closes #
**New**
**Changed**
**Removed**
> Updated text under “Asian scripts”

- src/pages/typography/type-basics.mdx
Removed “Headlines are preferred...” from here https://www.ibm.com/design/language/typography/type-basics#stacked-headlines
Closes #
**New**
**Changed**
**Removed**
> Removed “Headlines are preferred...”

- src/components/SwatchPaletteWidget/SwatchPalette.js
Closes #894 
Updates Alert Yellow30 and Orange40 PMS values
> update PMS values for orange and yellow

- src/pages/data-visualization/design/basics.mdx
AAdd Sketch master file resource card
> Add resource card to Design Basic page

- src/pages/typography/typeface.mdx
> Add new Plex video closes #988

- src/pages/typography/typeface.mdx
Also added “IBM Plex“ in front of Chinese in the first sentence.
Closes #
**New**
**Changed**
**Removed**
> Update “Asian scripts” to “Chinese scripts”

- src/pages/whats-new/index.mdx
Closes #
**New**
**Changed**
**Removed**
> Added Korean Plex JP announcement

- src/pages/typography/typeface.mdx
Got a list from @mjabbink with more languages that plex seems to support that aren't currently covered on this page.
**I'm only comparing the 2 lists and adding new items**, pls check thoroughly and make sure that these are valid. Mike could be a good resource to verify this
> docs(plex): update plex languages list

- src/components/TypesetStyle/TypesetStyle.js
Carries over https://github.com/carbon-design-system/carbon-website/pull/2657 to the IDL website.
> docs(typography): fix font family for quotation-02 style

- src/pages/typography/typeface.mdx
added an s to weights and removed and “and” because there were two back to back.
Closes #
**New**
**Changed**
**Removed**
> Fixed several typos

- src/components/TypesetExample/_typeset-example.scss
> fix: typography line spacing

- src/pages/infographics/technical-diagrams/design.mdx
- src/pages/infographics/technical-diagrams/usage.mdx
> fix: download not working on tech diagram page

- src/pages/infographics/technical-diagrams/usage.mdx
> fix: links

- src/pages/help/support.mdx
Copy and links for the support page has been updated.
> feat: update copy and links

- src/gatsby-theme-carbon/components/Footer/index.js
Closes [291](https://github.com/ibm-brand/center/issues/291) (Brand Center Issue)
Updated "Have questions?" on Footer component.
**Changed**
- Updated text on footer about "Have questions?" removing email and adding airtable form link.
> feat(footer): updated text and links

- src/pages/iconography/app-icons/design.mdx
Closes [320](https://github.com/ibm-brand/center/issues/320) (Brand Center Issue)
Updating the introduction paragraph on IDL > App icons > Design page
**Changed**
Change the introduction paragraph at the top of the IDL > App icons > Design page to:
"IBM app icons are visual symbols that represent products or services. They identify apps at a glance for users while serving as a unique expression of our brand. Every IBM app icon is rights restricted and should not be altered. An app icon should never be used in reference to any topic other than its name."
> feat: update App Icons > Design page with new initial paragraph

- package.json
- yarn.lock
> chore: release update

- yarn.lock
Reverts carbon-design-system/design-language-website#1286
> Revert "chore: bump @carbon/icons-react from 11.29.1 to 11.29.2"

- yarn.lock
Reverts carbon-design-system/design-language-website#1285
> Revert "chore: bump @carbon/pictograms-react from 11.51.1 to 11.51.2"

- yarn.lock
Reverts carbon-design-system/design-language-website#1284
> Revert "chore: bump @carbon/pictograms from 12.25.1 to 12.25.2"

- yarn.lock
Reverts carbon-design-system/design-language-website#1283
> Revert "chore: bump @carbon/icons from 11.29.1 to 11.29.2"

- yarn.lock
Reverts carbon-design-system/design-language-website#1277
> Revert "chore: bump @carbon/icons-react from 11.28.0 to 11.29.1"

- gatsby-node.js
Continuation of https://github.com/carbon-design-system/carbon/pull/15116 to unhide pictograms that were previously hidden.
> fix(idl-pictograms): unhide watsonx pictograms

- src/data/app-icons.yaml
Closes #1296
- remove duplicate data causing null section
- change category to stroke style from unassigned for IBM Health Pass Verifier icon
Ensure null and unassigned categories are no longer showing on App icons page
https://design-language-website-git-fork-al-aae8a0-carbon-design-system.vercel.app/iconography/app-icons/library
> fix(app-icons): remove duplicate data and fix category for unassigned

- src/pages/infographics/technical-diagrams/usage.mdx
update the link for the diagram.net build resource card
> Update usage - new link

- src/components/NonLatinScripts/NonLatinScripts.js
- src/components/TypeFaceSubFamilies/TypefaceSubFamilies.js
- src/components/TypeTester/TypeTester.js
- src/components/TypeTester/_type-tester.scss
- src/pages/index.mdx
- src/pages/typography/typeface.mdx
- src/pages/whats-new/index.mdx
Closes Brand issues 602, 603 and 604
Further copy reviews gathered some edit needs on the new content from the pages
**New**
- Added Plex Sans TC to the type tester on the Typeface page
**Changed**
- Minor changes on the Plex posts from What's new page
- Plenty of copy changes and edits on the Typeface page
**Removed**
- N/A
> WIP - Updates on Plex posts and Typeface page

- src/pages/ibm-logos/8-bar.mdx
- src/pages/resources.mdx
Closes N/A
Urgent request from Brand team to fix broken link for third party logo requests
Changelog
Changed
Changed links on resource cards on 8-bar and resources pages for third party logo requests
Removed
N/A
> fix(multiple): changed link for third party logo req cards
